### ISSUE TITLE
No matching export in styled-engine

### ISSUE THREAD

**Issue by mc706** [mui/toolpad#4257]
### Steps to reproduce

Link to live example: (required)

Steps:
1.`npx create-toolpad-app --studio example-app`
2.`cd example-app`
3.`npm run dev`

### Current behavior

```
✘ [ERROR] No matching export in "node_modules/@mui/styled-engine/index.js" for import "internal_processStyles"

    node_modules/@mui/system/createStyled/createStyled.js:2:29:
      2 │ ...tyledEngineStyled, { internal_processStyles as processStyles } f...
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~

4:15:45 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@mui/system/createStyled/createStyled.js:2:29: ERROR: No matching export in "node_modules/@mui/styled-engine/index.js" for import "internal_processStyles"
    at failureErrorWithLog (<>/node_modules/vite/node_modules/esbuild/lib/main.js:1472:15)
    at <>/node_modules/vite/node_modules/esbuild/lib/main.js:945:25
    at <>/node_modules/vite/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

```

### Expected behavior

Expected to be able to launch the studio from a clean install

### Context

Trying to get started on a new project

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
  Binaries:
    Node: 22.9.0 - ~/.nvm/versions/node/v22.9.0/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v22.9.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 129.0.6668.100
  npmPackages:
    @emotion/react:  11.13.3 
    @emotion/styled:  11.13.0 
    @mui/base:  5.0.0-beta.58 
    @mui/core-downloads-tracker:  6.1.3 
    @mui/icons-material:  6.1.1 
    @mui/lab:  6.0.0-beta.10 
    @mui/material:  6.1.1 
    @mui/private-theming:  6.1.3 
    @mui/styled-engine:  6.1.3 
    @mui/system:  6.1.1 
    @mui/types:  7.2.17 
    @mui/utils:  6.1.1 
    @mui/x-charts:  7.18.0 
    @mui/x-charts-vendor:  7.18.0 
    @mui/x-data-grid:  7.18.0 
    @mui/x-data-grid-premium:  7.18.0 
    @mui/x-data-grid-pro:  7.18.0 
    @mui/x-date-pickers:  7.18.0 
    @mui/x-date-pickers-pro:  7.18.0 
    @mui/x-internals:  7.18.0 
    @mui/x-license:  7.18.0 
    @mui/x-tree-view:  7.18.0 
    @toolpad/studio: latest => 0.7.0 
    @toolpad/studio-components:  0.7.0 
    @toolpad/studio-runtime:  0.7.0 
    @toolpad/utils:  0.7.0 
    @types/react:  18.3.11 
    react:  18.3.1 
    react-dom:  18.3.1 
    typescript:  5.5.4 
```
</details>

**Search keywords**: build internal_processStyles

**Comment by Janpot** [comment]
Thank you for reporting. We're tracking the issue [upstream](https://github.com/mui/toolpad/issues/4257). In the meantime you can force resolution of `@mui/styled-engine` to v6.1.1 in npm with
```tsx
// ./package.json
  "overrides": {
    "@mui/system@6.1.1": {
      "@mui/styled-engine": "6.1.1"
    }
  }
```

---

For pnpm users:

```tsx
// ./package.json
  "pnpm": {
    "overrides": {
      "@mui/system@6.1.1>@mui/styled-engine": "6.1.1"
    }
  },
```

For yarn users:

_still working on a workaround_

**Comment by bharatkashyap** [comment]
Verified to be working in the latest release
